# Generated by Django 3.1.2 on 2020-11-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20201107_1907'),
        ('sessions', '0001_initial'),
        ('purchases', '0002_auto_20201107_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='recipes',
            field=models.ManyToManyField(to='recipes.Recipe', verbose_name='рецепты'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='sessions.session', verbose_name='сессия'),
        ),
    ]
