# Generated by Django 3.1.2 on 2020-11-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201102_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredientforrecipe',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
