# Generated by Django 3.1.2 on 2020-11-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20201105_0527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientForRecipe',
            new_name='RecipeIngredient',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='recipes/'),
        ),
    ]
