# Generated by Django 3.1.2 on 2020-11-04 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201105_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='favourites',
            new_name='favorites',
        ),
    ]
