# Generated by Django 3.1.2 on 2020-11-11 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20201111_1912'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20201105_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='favorites',
            field=models.ManyToManyField(related_name='fans', to='recipes.Recipe', verbose_name='избранное'),
        ),
        migrations.AlterField(
            model_name='social',
            name='following',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='подписки'),
        ),
        migrations.AlterField(
            model_name='social',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
